version: '3.7'

services:
  db:
    build:
      context: ./mysql
    container_name: db
    restart: always
    tty: true
    networks:
      - nginx-network
    volumes:
      - ./mysql/volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=geccal_test
      - MYSQL_ROOT_PASSWORD=root

networks:
  nginx-network:
    driver: bridge
