version: 2.1
orbs:
  heroku: circleci/heroku@1.0.1
  node: circleci/node@3.0.0

jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - heroku/deploy-via-git:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - staging
